site_name: SlamData Docs
site_url: http://docs.slamdata.com
site_description: SlamData Documentation
site_favicon: favicon.png
use_directory_urls: true
theme: bootstrap
pages:
- Home: index.md
- Administration Guide : administration-guide.md
- Users Guide : users-guide.md
