site_name: SlamData Docs
site_url: http://docs.slamdata.com
site_description: SlamData Documentation
site_favicon: favicon.png
use_directory_urls: true
theme: readthedocs
pages:
- Home: index.md
- Administration Guide : administration-guide.md
- SQL² Reference Guide : sql-squared-reference.md