site_name: SlamData Docs
site_url: http://docs.slamdata.com
site_description: SlamData Documentation
site_favicon: favicon.png
use_directory_urls: false
theme: readthedocs
pages:
- Home : index.md
- Administration Guide : administration-guide.md
- Users Guide : users-guide.md
- Securing SlamData : securing-slamdata.md
- Troubleshooting FAQ : troubleshooting-faq.md
- Reference (SQL²) : sql-squared-reference.md
- Reference (SlamDown) : slamdown-reference.md
- Reference (API) : api-reference.md
